name: Azure Static Web Apps CI/CD for Zamir.dev

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS Node.js version

      # Install project dependencies (fs-extra, markdown-it, gray-matter)
      - name: Install dependencies
        run: npm install

      # Run your custom build script to process Markdown and generate HTML
      - name: Run custom build script
        run: npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_OCEAN_07FBAB803 }} # This secret is automatically created by Azure
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # IMPORTANT: These paths are relative to the root of your GitHub repository
          # app_location: The folder containing your build.js, package.json, and source files
          # output_location: The folder where your static HTML, CSS, JS are *after* the build script runs
          app_location: "/" # The root of your repository (where package.json, build.js are)
          output_location: "public" # The 'public' folder created by build.js for deployment
          api_location: "" # Leave empty if no Azure Functions API
